scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Set up code signing
        script: |
          keychain initialize
          # Hna Codemagic khasso i-fetchi l-certificates mn Apple
          app-store-connect fetch-signing-files "com.your.bundle.id" --project-id "YOUR_APP_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS release
        script: |
          # Darouri t-زيد --export-method app-store
          flutter build ipa --release --export-method app-store